services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./Backend/src:/app/src
    command: bash src/start.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - formbar

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./Frontend:/app
    command: pnpm dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - formbar

  postgres:
    image: postgres:alpine
    container_name: rc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formbar
    ports:
      - "5432:5432"
    volumes:
      - rc_postgres_data:/var/lib/postgresql/data
    networks:
      - formbar

  redis:
    image: redis:alpine
    container_name: rc-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - formbar

  mongodb:
    image: mongo:latest
    container_name: rc-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - formbar

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rc-rustfs
    restart: unless-stopped
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_CONSOLE_ENABLE: "true"
    ports:
      - "9001:9001" # Web Console
      - "9002:9000" # S3 API
    volumes:
      - rustfs_data:/data
    networks:
      - formbar

  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    container_name: rc-whatsapp
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - whatsapp_data:/app/storages
    command:
      - rest
      - --port=3001
      - --debug=true
      - --os=Formbar
      - --account-validation=false
      - --webhook="http://backend:8000/webhook"
      - --webhook-secret="${WHATSAPP_WEBHOOK_SECRET}"
      - --basic-auth="${WHATSAPP_BASIC_AUTH}"
      - --webhook-events="message"
    networks:
      - formbar

networks:
  formbar:
    driver: bridge

volumes:
  rc_postgres_data:
  redis_data:
  mongodb_data:
  clickhouse_data:
  rustfs_data:
  whatsapp_data:
