import uuid
from typing import Any, Dict, List, Optional
from datetime import datetime

from pydantic import BaseModel, Field

# --- Block Definitions --- #


class FormBlockOptions(BaseModel):
    label: str
    value: str


class FormBlockConfig(BaseModel):
    # Common configurations
    required: bool = False
    placeholder: Optional[str] = None
    helperText: Optional[str] = None

    # Text Input specific
    minLength: Optional[int] = None
    maxLength: Optional[int] = None
    validationType: Optional[str] = None  # e.g. "email", "number", "url"

    # Number specific
    min: Optional[float] = None
    max: Optional[float] = None

    # Select / Radio / Checkbox specific
    options: Optional[List[FormBlockOptions]] = None
    allowMultiple: bool = False  # for dropdown/select

    # File specific
    maxFileSizeStr: Optional[str] = None  # e.g. "5MB"
    allowedFileTypes: Optional[List[str]] = None  # e.g. [".pdf", ".jpg"]

    # UPI specific
    upiId: Optional[str] = None
    upiAmount: Optional[str] = None

    # Quiz specific
    correctAnswer: Optional[Any] = None
    points: int = 1
    timerSeconds: Optional[int] = None

    # Conditional Logic
    logic: List[Dict[str, Any]] = Field(default_factory=list)


class FormBlock(BaseModel):
    id: str = Field(..., description="Unique ID for the block generated by frontend")
    type: str = Field(
        ...,
        description="Type of block: text, email, number, select, radio, checkbox, file, date, etc.",
    )
    label: str
    config: FormBlockConfig = Field(default_factory=FormBlockConfig)


class FormSchema(BaseModel):
    blocks: List[FormBlock] = Field(default_factory=list)


# --- DTOs --- #


class FormCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=255)
    description: Optional[str] = None

class FormGenerationRequest(BaseModel):
    prompt: str
    name: str = "AI Generated Form"
    description: Optional[str] = "Form generated by AI"


class FormResponse(BaseModel):
    id: uuid.UUID
    organization_id: uuid.UUID
    organization_slug: Optional[str] = None
    name: str
    slug: str
    description: Optional[str] = None
    is_published: bool
    theme: str = "minimal"
    is_quiz: bool = False
    expires_at: Optional[datetime] = None
    redirect_url: Optional[str] = None
    schema_snapshot: Dict[str, Any]
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class FormUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    is_published: Optional[bool] = None
    theme: Optional[str] = None
    slug: Optional[str] = None
    is_quiz: Optional[bool] = None
    expires_at: Optional[datetime] = None
    redirect_url: Optional[str] = None


class FormEventCreate(BaseModel):
    event_type: str
    payload: Dict[str, Any]


class FieldResponse(BaseModel):
    block_id: str
    value: Any


class FormSubmission(BaseModel):
    form_id: uuid.UUID
    organization_id: uuid.UUID
    responses: List[FieldResponse]
    submitted_by_whatsapp: bool = False
    whatsapp_phone_number: Optional[str] = None
