import uuid
from typing import Any, Dict, List, Optional
from datetime import datetime

from pydantic import BaseModel, Field

# --- Block Definitions --- #


class FormBlockOptions(BaseModel):
    label: str
    value: str


class FormBlockConfig(BaseModel):
    # Common configurations
    required: bool = False
    placeholder: Optional[str] = None
    helperText: Optional[str] = None

    # Text Input specific
    minLength: Optional[int] = None
    maxLength: Optional[int] = None

    # Number specific
    min: Optional[float] = None
    max: Optional[float] = None

    # Select / Radio specific
    options: Optional[List[FormBlockOptions]] = None

    # File specific
    maxFileSizeStr: Optional[str] = None  # e.g. "5MB"
    allowedFileTypes: Optional[List[str]] = None  # e.g. [".pdf", ".jpg"]


class FormBlock(BaseModel):
    id: str = Field(..., description="Unique ID for the block generated by frontend")
    type: str = Field(
        ...,
        description="Type of block: text, email, number, select, radio, checkbox, file, date, etc.",
    )
    label: str
    config: FormBlockConfig = Field(default_factory=FormBlockConfig)


class FormSchema(BaseModel):
    blocks: List[FormBlock] = Field(default_factory=list)


# --- DTOs --- #


class FormCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=255)
    description: Optional[str] = None


class FormResponse(BaseModel):
    id: uuid.UUID
    organization_id: uuid.UUID
    name: str
    description: Optional[str] = None
    is_published: bool
    schema_snapshot: Dict[str, Any]
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class FormUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    is_published: Optional[bool] = None


class FormEventCreate(BaseModel):
    event_type: str
    payload: Dict[str, Any]
